### ISSUE TITLE
Switching languages in SSR

### ISSUE THREAD

**Issue by attalbialami** [Fafnur/fafnur#2]
Hello @Fafnur 

I would like to know how you manage to switch between languages in the project while running the Express server used for the SSR.

Is it possible to switch languages, or is it restricted to one language per build?

Last question, how do you do to deploy the app in SSR?

Thank you in advance for your answers!

Best regards,

**Comment by Fafnur** [comment]
@attalbialami I answered in https://github.com/Fafnur/fafnur/issues/1.

If you don't use SSR, you can do this:
https://angular.dev/guide/i18n/deploy#nginx-example


But, if you use SSR, then you need to run a server for each language:

```bash
PORT=4000 node dist/apps/fafn.ru/server/ru/server.mjs
PORT=4001 node dist/apps/fafn.ru/server/en/server.mjs
```

Then using nginx you can try to proxy the site. 

In my case, I simply separated the sites into different domains, which allowed me to avoid using proxying.
